export { default as Cswiper } from './swiper' // 轮播图
export { default as PicGroup } from './picgroup' // 单图组
export { default as ShowCase } from './showcase' // 图片橱窗
export { default as ShowVideo } from './video' // 视频
export { default as AirtcleList } from './articlegroup' // 文章组
export { default as TouTiao } from './toutiao' // 头条
export { default as Search } from './search' // 搜索框
export { default as Notice } from './notice' // 公告组
export { default as Navigator } from './navigator' // 导航组
export { default as ShopPing } from './shopping' // 商品组
export { default as Coupon } from './coupon' // 优惠券
export { default as PingShop } from './pinshop' // 拼团商品
export { default as KanJia } from './kanjia' // 砍价商品
export { default as MenDian } from './mendian' // 线下门店
export { default as Kefu } from './kefy' // 客服
export { default as Empty } from './empty' // 空白
export { default as Fuwenben } from './fuwenben' // 富文本
export { default as Fuzhuxian } from './fuzhuxian' // 辅助线
